In [1]:
#!pip install jupyter pandas yfinance aiohttp polars polars-talib==0.1.5 cryptography

In [2]:
from datetime import datetime
from data_providers import DataProviderFactory
import sys
sys.path.append('C:/Users/fwmac/Documents/Projects/Bot-Club/app/backend_services/src/models/')
from user_config import ConfigEncryption
from cryptography.fernet import Fernet

In [3]:

data_provider_client = DataProviderFactory.get_provider(provider_name='polygon', api_key='8XvjiWID5oKnXHWl2O0n7Pc6iyAoyKG3')

start_date = datetime.strptime('2025-01-02', '%Y-%m-%d')
end_date = datetime.strptime('2025-01-10', '%Y-%m-%d')

In [4]:
pltr_async = data_provider_client.get_historical_data(symbol='PLTR', 
                                         start_date=start_date, 
                                         end_date=end_date,
                                         timeframe='15m')


pltr_data = await pltr_async
pltr_data.head()

shape: (5, 7)
┌────────────────────────────────┬───────┬───────┬───────┬───────┬─────────┬─────────┐
│ t                              ┆ open  ┆ high  ┆ low   ┆ close ┆ volume  ┆ vwap    │
│ ---                            ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---     ┆ ---     │
│ datetime[ms, America/New_York] ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64     ┆ f64     │
╞════════════════════════════════╪═══════╪═══════╪═══════╪═══════╪═════════╪═════════╡
│ 2025-01-02 04:00:00 EST        ┆ 76.19 ┆ 76.88 ┆ 76.19 ┆ 76.57 ┆ 77035.0 ┆ 76.6356 │
│ 2025-01-02 04:15:00 EST        ┆ 76.56 ┆ 76.72 ┆ 76.39 ┆ 76.72 ┆ 61922.0 ┆ 76.5216 │
│ 2025-01-02 04:30:00 EST        ┆ 76.72 ┆ 76.72 ┆ 76.44 ┆ 76.58 ┆ 36945.0 ┆ 76.5609 │
│ 2025-01-02 04:45:00 EST        ┆ 76.6  ┆ 76.66 ┆ 76.53 ┆ 76.6  ┆ 15591.0 ┆ 76.6104 │
│ 2025-01-02 05:00:00 EST        ┆ 76.64 ┆ 76.64 ┆ 76.47 ┆ 76.55 ┆ 29157.0 ┆ 76.5463 │
└────────────────────────────────┴───────┴───────┴───────┴───────┴─────────┴─────────┘

In [5]:
alpaca_client = DataProviderFactory.get_provider(provider_name='alpaca', 
                                                        api_key='PKGJOUQ37TRR4OTMSAKU',
                                                        secret_key='lbrDYLeZd2IeEpUyiNoiONKmM7ZNjXXZXY1eUolq')

In [6]:
pltr_alpaca_async = alpaca_client.get_historical_data(symbol='PLTR', 
                                         start_date=start_date, 
                                         end_date=end_date,
                                         timeframe='15m')

pltr_alpaca = await pltr_alpaca_async
pltr_alpaca.head()

shape: (5, 7)
┌────────────────────────────────┬───────┬───────┬───────┬───────┬────────┬───────────┐
│ t                              ┆ open  ┆ high  ┆ low   ┆ close ┆ volume ┆ vwap      │
│ ---                            ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---       │
│ datetime[μs, America/New_York] ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ i64    ┆ f64       │
╞════════════════════════════════╪═══════╪═══════╪═══════╪═══════╪════════╪═══════════╡
│ 2025-01-02 04:00:00 EST        ┆ 76.19 ┆ 76.88 ┆ 76.19 ┆ 76.57 ┆ 77035  ┆ 76.638201 │
│ 2025-01-02 04:15:00 EST        ┆ 76.56 ┆ 76.72 ┆ 76.39 ┆ 76.72 ┆ 61922  ┆ 76.517554 │
│ 2025-01-02 04:30:00 EST        ┆ 76.72 ┆ 76.72 ┆ 76.44 ┆ 76.58 ┆ 36945  ┆ 76.55855  │
│ 2025-01-02 04:45:00 EST        ┆ 76.6  ┆ 76.66 ┆ 76.53 ┆ 76.6  ┆ 15591  ┆ 76.610867 │
│ 2025-01-02 05:00:00 EST        ┆ 76.64 ┆ 76.64 ┆ 76.47 ┆ 76.55 ┆ 29157  ┆ 76.54399  │
└────────────────────────────────┴───────┴───────┴───────┴───────┴────────┴───────────┘